version: 2

references:
  workspace_root: &workspace_root ~/thincloud-embedded-c-sdk

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

defaults: &defaults
  working_directory: *workspace_root
  docker:
    - image: ubuntu:rolling

aliases:
  - &run-build-test
    run:
      name: Install Dependencies
      command: |
        apt-get update && apt-get -y install python gcc g++ make git autoconf automake libtool
        cd ~
        git clone https://github.com/aws/aws-iot-device-sdk-embedded-C
        git clone https://github.com/ARMmbed/mbedtls aws-iot-device-sdk-embedded-C/external_libs/mbedtls
        git clone https://github.com/json-c/json-c
        cd json-c
        sh autogen.sh
        ./configure --prefix=/usr --disable-static --enable-threading
        make
        make install
        make check
        cd ~/thincloud-embedded-c-sdk/tests
        make
        ./tests

#################### JOBS ####################

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *run-build-test
      - persist_to_workspace:
          root: ~/thincloud-embedded-c-sdk
          paths:
            - .
#################### WORKFLOWS ####################

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
